src/core/urls.py
from django.urls import path
from django.contrib.auth import urls
from django.conf.urls import include

from . import views

# both for the link names and the view names, try to stick to this:

# projects -> list
# if the singular version already has an 's' at the end, use:
# thesis_list -> list

# project -> project view
# project_form -> add new/edit existing project

app_name = 'core'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('home', views.home, name='home'),
    path('search', views.search, name='search'),
    path('more', views.empty, name='more'),
    path('resources/videos', views.videos, name='videos'),
    path('resources/videos/<int:id>', views.video, name='video'),

    path('community/news', views.articles, {'parent': 'news'}, name='news'),
    path('community/news/<int:id>', views.article, name='news'),
    path('community/blog', views.articles, {'parent': 60}, name='blog'),
    path('community/blog/<int:id>', views.article, name='blog'),
    path('community/events', views.articles, {'parent': 'events'}, name='events'),
    path('community/events/<int:id>', views.article, name='event'),

    path('news_events', views.news_and_events, name='news_and_events'),
    path('page/<slug:slug>', views.page, name='page'),
    path('cities', views.sectionpage, { 'id': 33}, name='sectionpage'),
    path('cities/page/<slug:slug>', views.sectionpage, name='sectionpage'),
    path('about', views.team, name='about'),
    path('about/team', views.team, name='team'),
    path('about/task-forces', views.taskforces, name='taskforces'),
    path('about/task-forces/<slug:slug>', views.taskforce, name='taskforce'),

    path('community/people', views.people, name='people'),
    path('community/people/<int:id>', views.peopledetails, name='peopledetails'),
    path('community/user/<int:id>', views.peopledetails, name='userdetails'),

    #path('community/research', views.projects, {'type': 'research', 'status': 'ongoing', 'page': 50}, name='research_projects'),
    #path('community/research/<int:id>', views.project_view, {'type': 'research', 'status': 'ongoing'}, name='research_project'),
    #path('community/research/past', views.projects, {'type': 'research', 'status': 'finished', 'page': 51}, name='past_research_projects'),
    #path('community/research/past/<int:id>', views.project_view, {'type': 'research', 'status': 'finished'}, name='past_research_project'),
    #path('community/projects', views.projects, {'type': 'projects', 'status': 'ongoing', 'page': 57}, name='projects'),
    #path('community/projects/<int:id>', views.project_view, {'type': 'projects', 'status': 'ongoing'}, name='project'),
    #path('community/projects/past', views.projects, {'type': 'projects', 'status': 'finished', 'page': 56}, name='past_projects'),
    #path('community/projects/past/<int:id>', views.project_view, {'type': 'projects', 'status': 'finished'}, name='past_project'),
    
    path('resources/journals', views.journals, name='journals'),
    path('resources/journals/<int:id>', views.journal, name='journal'),

    path('community/organizations/<int:id>', views.organization, name='organization'),
    path('community/organizations/<slug:type>', views.organizations, name='organizations'),

    path('community/research/create', views.project_form, name='project_form'),
    path('community/research/<slug:type>', views.projects, name='projects'),
    path('community/research/<slug:type>/<int:id>', views.project, name='project'),

    path('resources', views.journals, name='resources_home'),
    path('community', views.empty, name='community_home'),
    path('register', views.register),

    path('<slug:slug>', views.section_home, name='section_home'),

    path('about/<slug:slug>', views.page, name='about'),
    path('community/<slug:slug>', views.page, name='community'),
    path('resources/data/<slug:slug>', views.page, name='data'),
    path('resources/tools/<slug:slug>', views.page, name='tools'),
    path('services/support/<slug:slug>', views.page, name='support'),
    path('services/research/<slug:slug>', views.page, name='research'),
    path('services/stakeholders-engagement/<slug:slug>', views.page, name='engagement'),
    path('services/support/<slug:slug>', views.page, name='support'),
    path('contact', views.contact, name='contact'),
    path('literature', views.literature, name='literature'),
    path('publishers', views.publishers, name='publishers'),
    path('publishers/<int:id>', views.publisher, name='publisher'),
    path('resources/podcasts', views.references, {'type': 24}),
    path('resources/reports', views.references, {'type': 27}),
    path('resources/presentations', views.references, {'type': 25}),
    path('resources/publications', views.references, name='references'),
    path('resources/publication/<int:id>', views.reference),
    path('resources/publications/<int:id>', views.reference, name='reference'),
    path('resources/publications/<int:id>/edit', views.referenceform, name='editreference'),
    path('resources/publications/add', views.referenceform, name='newreference'),
    path('resources/publications/create/<int:dataset>', views.referenceform, name='newflowreference'),
    path('resources/publications/tags/<int:tag>', views.references, name='tag_search'),
    path('resources/publications/<slug:slug>', views.page, name='publications'),
    path('resources/<slug:slug>', views.page, name='resources'),
    path('resources/publications/search/ajax', views.reference_search_ajax, name='reference_search_ajax'),
    path('tags/ajax', views.tag_ajax, name='tag_ajax'),

    path('admin/people', views.admin_people_list, name='admin_people_list'),
    path('admin/members', views.admin_member_list, name='admin_member_list'),
    path('admin/people/create', views.admin_people, name='admin_people_create'),
    path('admin/people/<int:id>', views.admin_people, name='admin_people'),
    path('admin/videos', views.admin_video_list, name='admin_video_list'),
    path('admin/videos/create', views.admin_video, name='admin_video_create'),
    path('admin/videos/<int:id>', views.admin_video, name='admin_video'),
    path('admin/videocollections', views.admin_videocollections, name='admin_videocollections'),
    path('admin/videocollections/create', views.admin_videocollection, name='admin_videocollection_create'),
    path('admin/videocollections/<int:id>', views.admin_videocollection, name='admin_videocollection'),
    path('admin/articles/<int:id>', views.admin_article, name='admin_article'),
    path('admin/events/create', views.admin_article, {'type': 'event'}, name='admin_article'),
    path('admin/articles/create/parent=<int:parent>', views.admin_article, name='admin_article_parent'),
    path('admin/project/create', views.admin_project, name='admin_project_create'),
    path('admin/project/<int:id>', views.admin_project, name='admin_project'),
    path('admin/projects', views.admin_project_list, name='admin_project_list'),
    path('admin/projects/<slug:status>', views.admin_project_list, name='admin_project_list'),
    path('admin/tags', views.admin_tag_list, name='admin_tag_list'),
    path('admin/tags/create', views.admin_tag, name='admin_tag'),
    path('admin/tags/<int:id>', views.admin_tag, name='admin_tag'),
    path('admin/tags/<int:parent>/child', views.admin_tag, name='admin_tag'),
    path('admin/publications/<int:id>', views.referenceform, name='admin_reference'),
    path('admin/publications/<int:id>/tags', views.admin_referencetags, name='admin_referencetags'),
    path('admin/publications', views.admin_references, name='admin_references'),

    path('admin/organizations', views.admin_organization_list, name='admin_organization_list'),
    path('admin/organizations/<int:id>', views.admin_organization, name='admin_organization'),
    path('admin/organizations/create', views.admin_organization, name='admin_organization'),
    path('admin/organizations/create/<slug:slug>', views.admin_organization, name='admin_organization_referencespace'),

#temp
    path('updateorgs', views.updateorgs),
]

src/ie/urls.py
from django.urls import include, path
from django.contrib import admin

" These two are to make file uploads work "
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('data/', include('staf.urls')),
    path('intranet/', include('team.urls')),
    path('', include('core.urls')),
    path('cities/', include('multiplicity.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/team/urls.py
from django.urls import path
from django.contrib.auth import urls
from django.conf.urls import include

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('controlpanel', views.controlpanel, name='controlpanel'),
    path('category/<int:id>', views.category),
    path('taskforce/<int:id>', views.taskforce, name='taskforce'),
    path('taskforce/<int:category>/task', views.ticket, name='newticket'),
    path('taskforce/<int:id>/leave', views.leavetaskforce, name='leavetaskforce'),
    path('tickets', views.ticketlist, name='tickets'),
    path('tickets/<int:id>', views.ticketdetails, name='ticket'),
    path('tickets/<int:id>/status/<slug:status>', views.ticketstatus, name='ticketstatus'),
    path('tickets/<int:id>/startdiscussion', views.ticketdiscussion, name='ticketdiscussion'),
    path('tickets/<int:id>/progress', views.ticketprogress, name='ticketprogress'),
    path('tickets/<int:id>/assign_to/<int:person>', views.ticketperson, name='ticketperson'),
    path('tickets/<int:id>/edit', views.ticket, name='editticket'),
    path('category/<int:id>/view', views.opencategory, name='viewcategory'),
    path('category/<int:id>/config', views.categoryconfig, name='categoryconfig'),
    path('category/<int:id>/config/save', views.saveconfig, name='saveconfig'),
    path('category/<int:id>/<int:topic>', views.category),
    path('topic/<int:id>', views.topic),
    path('topic/<int:id>/view', views.opentopic, name='topic'),
    path('topic/<int:id>/subscription/<slug:type>', views.subscribetopic, name='topic_subscribe'),
    path('topic/<int:id>/edit', views.edittopic, name='edittopic'),
    path('topic/create', views.createtopic, name='createtopic'),
    path('topic/<int:id>/message', views.createmessage),
    path('message/<int:id>/delete', views.deletemessage, name='deletemessage'),
    path('register', views.register),
    path('taskforces', views.taskforces, name='taskforces'),
    path('search', views.search, name='search'),
    path('profile', views.profile, name='memberprofile'),
    path('profile/save', views.saveprofile, name='saveprofile'),
    path('reports/tickets', views.ticketreport, name='ticketreport'),
    path('projects', views.projects, name='projects'),
    path('projects/<int:id>', views.project, name='project'),
    path('projects/create', views.project, name='createproject'),
]

src/templates/core/admin/organization.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}Organization{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li><a href="{% url 'core:admin_organization_list' %}">Organizations</a></li>
        {% if info.id %}
          <li class="active">{{ info.title }}</li>
        {% else %}
          <li class="active">Create new organization</li>
        {% endif %}
    </ol>

  <h2>{{ info|yesno:"Edit details,Add new organization" }}</h2>
  <form method="post" class="form form-horizontal boxit pad-all" enctype="multipart/form-data">

    {% bootstrap_form form layout='horizontal' %}

    <div class="form-group">
      <label class="col-md-3 control-label" for="processes">Processes</label>
      <div class="col-md-9">
        <select class="form-control" name="process" id="processes" multiple>
          {% for details in processes %}
            <option value="{{ details.id }}" {% if details in info.processes.all %}selected{% endif %}>{{ details.code }}. {{ details.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    {% buttons %}
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-success">Save</button>
      </div>
    {% endbuttons %}
    {% csrf_token %}
  </form>

{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'ie/js/summernote/summernote.min.css' %}" />
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static 'ie/js/summernote/summernote.min.js' %}"></script>
<script type="text/javascript">
$(function(){
  $("#id_date").attr("type", "date");
  $("#id_website").attr("placeholder", "'youtube' or 'vimeo' (lowercase, no spaces, no quotation marks)");
  $('#id_description').summernote({
      height : '230px'
  });
  $("#id_parent").select2();
  $("#id_people").select2();
  $("#id_reference_spaces").select2();
});
</script>
{% endblock %}

src/templates/core/admin/people.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}People{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li><a href="{% url 'core:admin_people_list' %}">People</a></li>
        <li class="active">{{ info.firstname }} {{ info.lastname }}</li>
    </ol>

  <h2>{{ info|yesno:"Edit details,Add new person" }}</h2>
  <form method="post" class="form form-horizontal boxit pad-all" enctype="multipart/form-data">
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-success">Save</button>
      </div>
    {% endbuttons %}
    {% csrf_token %}
  </form>

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}
<script type="text/javascript">
$(function(){
  $("#id_member_since").attr("type", "date");
});
</script>
{% endblock %}

src/templates/core/admin/people.list.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}People{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">{{ volunteers|yesno:"Volunteers,People" }}</li>
    </ol>

  <h3>{{ volunteers|yesno:"Volunteers,People" }}</h3>

  <div class="row">
    <div class="col-lg-12">
        <div class="boxit pad-all">
          <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>Name</th>
                <th>City</th>
                <th>E-mail</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
            {% for details in list %}
              <tr>
                <td>{{ details.firstname }} {{ details.lastname }}</td>
                <td>{{ details.city.name }}</td>
                <td>{{ details.email }}</td>
                <td><a class="btn btn-info" href="{% url 'core:admin_people' details.id %}"><i class="fa fa-pencil"></i> Edit</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
    </div>
  <p class="pad-top"><a href="{% url 'core:admin_people_create' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Add new person</a></p>
</div>


{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/core/admin/project.list.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Projects{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Projects</li>
    </ol>

  <h3>Projects</h3>

          <ul class="nav nav-tabs">
            <li {% if tab == 'published' %} class="active"{% endif %}><a href="{% url 'core:admin_project_list' 'published' %}">Published</a></li>
            <li {% if tab == 'pending' %} class="active"{% endif %}><a href="{% url 'core:admin_project_list' 'pending' %}">Pending review</a></li>
            <li {% if tab == 'deleted' %} class="active"{% endif %}><a href="{% url 'core:admin_project_list' 'deleted' %}">Deleted</a></li>
          </ul>

  <div class="row">
    <div class="col-lg-12">
        <div class="boxit pad-all">
          <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
            {% for details in list %}
              <tr>
                <td><a href="{% url 'core:admin_project' details.id %}">{{ details.name|truncatewords:10 }}</a></td>
                <td>{{ details.get_type_display }}</td>
                <td>{{ details.get_status_display }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
    </div>
  <p class="pad-top"><a href="{% url 'core:admin_project_create' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Add new project</a></p>
</div>


{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/core/admin/reference.tags.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}Tags{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

  <ol class="breadcrumb">
      <li><a href="./"><i class="pli-home"></i></a></li>
      <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
      <li><a href="{% url 'core:references' %}">Publications</a></li>
      <li><a href="{% url 'core:admin_reference' info.id %}">{{ info.title|truncatechars:40 }}</a></li>
        <li class="active">Tags</li>
  </ol>

  <h2>Edit tags</h2>

  <form method="post" class="form form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">Tags</label>
      <div class="col-sm-10">
        <select name="tags" class="form-control select2" multiple>
          {% for details in tags %}
            <option value="{{ details.id }}" {% if details in info.tags.all %}selected{% endif %}>{{ details.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Save</button>
      </div>
    </div>
  </form>

  <h3>Browse tag tree</h3>

  <p>Use the list below to see which tags exist.</p>

  <div id="tree"></div>

  <p><a href="{% url 'core:admin_tag_list' %}" target="_blank">Edit tag list</a></p>

{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/mar10/fancytree@2/dist/skin-lion/ui.fancytree.min.css" />
<style type="text/css">
#tree{overflow:hidden}
#details{margin-top:20px}
</style>
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/mar10/fancytree@2/dist/jquery.fancytree-all-deps.min.js"></script>
<script type="text/javascript">
$(function(){
    // Load tree from Ajax JSON
    $("#tree").fancytree({
      source: 
        [
          {% for details in parent_tags %}
            {title: "{{ details.name }}", key: "{{ details.id }}", lazy: true},
          {% endfor %}
        ]
      ,
			lazyLoad: function(event, data){
        var node = data.node;
				data.result = $.ajax({
					url: "{% url 'core:tag_ajax' %}",
					dataType: "json",
          data: {mode: "children", parent: node.key},
				});
			},
      activate: function(event, data) {
        var node = data.node;
      },
		});
    
});

</script>
{% endblock %}

src/templates/core/admin/references.list.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Publications{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Publications</li>
    </ol>

  <h3>Publications</h3>

  <div class="row">
    <div class="col-lg-12">
        <div class="boxit pad-all">
          <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Date</th>
                <th>Added</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
            {% for details in list %}
              <tr>
                <td><a href="{% url 'core:admin_reference' details.id %}">{{ details.id }}</a></td>
                <td>{{ details.title|truncatewords:10 }}</td>
                <td>{{ details.year }}</td>
                <td>{{ details.date_added }}</td>
                <td>{{ details.status }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
    </div>
  <p class="pad-top"><a href="{% url 'core:newreference' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Add new publication</a></p>
</div>


{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/core/admin/tag.html
{% extends 'multiplicity/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block title %}Tag{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li><a href="{% url 'core:admin_tag_list' %}">Tags</a></li>
        {% if info.id %}
          <li class="active">{{ info.name }}</li>
        {% else %}
          <li class="active">Create new tag</li>
        {% endif %}
    </ol>

  <h2>{{ info|yesno:"Edit details,Add new tag" }}</h2>
  <form method="post" class="form form-horizontal boxit pad-all" enctype="multipart/form-data">

    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}
      <div class="col-sm-offset-3 col-sm-9">
        <button type="submit" class="btn btn-success">Save</button>
      </div>
    {% endbuttons %}
    {% csrf_token %}
  </form>

{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'ie/js/summernote/summernote.min.css' %}" />
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static 'ie/js/summernote/summernote.min.js' %}"></script>
<script type="text/javascript">
$(function(){
  $("#id_date").attr("type", "date");
  $("#id_website").attr("placeholder", "'youtube' or 'vimeo' (lowercase, no spaces, no quotation marks)");
  $('#id_description').summernote({
      height : '230px'
  });
  $("#id_people").select2();
});
</script>
{% endblock %}

src/templates/core/admin/videocollections.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Video Collections{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Video Collections</li>
    </ol>

  <h3>Video Collections</h3>

  <div class="row">
    <div class="col-lg-12">
        <div class="boxit pad-all">
          <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>Title</th>
                <th>Options</th>
              </tr>
            </thead>
            <tbody>
            {% for details in list %}
              <tr>
                <td>{{ details.title }}</td>
                <td><a class="btn btn-info" href="{% url 'core:admin_videocollection' details.id %}"><i class="fa fa-pencil"></i> Edit</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
    </div>
  <p class="pad-top"><a href="{% url 'core:admin_videocollection_create' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Add new video collection</a></p>
</div>


{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/core/admin/videos.list.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}People{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li><a href="./"><i class="pli-home"></i></a></li>
        <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
        <li class="active">Videos</li>
    </ol>

  <h3>Videos</h3>

  <div class="row">
    <div class="col-lg-12">
        <div class="boxit pad-all">
          <table class="table table-striped datatable">
            <thead>
              <tr>
                <th>Title</th>
                <th>Date</th>
                <th>Author</th>
                <th>Options</th>
              </tr>
            </thead>
            <tbody>
            {% for details in list %}
              <tr>
                <td>{{ details.title }}</td>
                <td>{{ details.date }}</td>
                <td>{{ details.author }}</td>
                <td><a class="btn btn-info" href="{% url 'core:admin_video' details.id %}"><i class="fa fa-pencil"></i> Edit</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        </div>
    </div>
  <p class="pad-top"><a href="{% url 'core:admin_video_create' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Add new video</a></p>
</div>


{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}