src/ie/urls.py
from django.urls import include, path
from django.contrib import admin

" These two are to make file uploads work "
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('data/', include('staf.urls')),
    path('intranet/', include('team.urls')),
    path('', include('core.urls')),
    path('cities/', include('multiplicity.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/multiplicity/urls.py
from django.urls import path

from . import views

app_name = 'multiplicity'
urlpatterns = [

    # Admin
    path('admin/locations', views.admin_locations, name='admin_locations'),
    path('admin/locations/<int:id>', views.admin_location, name='admin_location'),
    path('admin/locations/create', views.admin_location, name='admin_location_create'),

    path('admin/referencespaces/<slug:type>', views.admin_referencespaces, name='admin_referencespaces'),
    path('admin/referencespaces/<slug:type>/<int:id>', views.admin_referencespace, name='admin_referencespace'),
    path('admin/referencespaces/<slug:type>/<int:referencespace>/location', views.admin_location, name='admin_referencespace_location'),
    path('admin/referencespaces/<slug:type>/create', views.admin_referencespace, name='admin_referencespace_create'),

    path('admin/<slug:city>/overview', views.admin_data_overview, name='admin_data_overview'),

    path('admin/datasettype', views.admin_datasettypes, name='admin_datasettypes'),
    path('admin/datasettype/<int:id>', views.admin_datasettype, name='admin_datasettype'),
    path('admin/datasettype/create', views.admin_datasettype, name='admin_datasettype'),

    path('admin/referencephotos', views.admin_referencephoto, name='admin_referencephotos'),
    path('admin/referencephotos/<int:id>', views.admin_referencephoto, name='admin_referencephoto'),
    path('admin/referencephotos/create', views.admin_referencephoto, name='admin_referencephoto'),

    # General
    path('table/datasets/<int:dataset>', views.datatable, name='datatable_dataset'),

    path('', views.index, name='index'),
    path('<slug:city>/research', views.research, name='research'),

    #path('<slug:city>/material-stocks/<slug:type>', views.flow, name='stock'),

    path('<slug:city>/material-flows/<slug:topic>', views.datasets_overview, name='flows'),
    path('<slug:city>/material-stocks/<slug:topic>', views.datasets_overview, {'type': 'stocks' }, name='stocks'),
    path('<slug:city>/energy-flows/<slug:topic>', views.datasets_overview, {'type': 'energy'}, name='energy_flows'),

    #path('<slug:city>/material-flows/<slug:slug>', views.overview, name='overview_flows'),
    #path('<slug:city>/material-flows/<slug:slug>/<slug:type>', views.flow, name='flow'),
    #path('<slug:city>/material-stocks', views.overview, {'slug': 'material-stocks' }, name='overview_stocks'),

    path('<slug:city>/profile/<slug:topic>', views.topic, name='topic'),
    #path('<slug:city>/<slug:topic>', views.topic, name='topic'),

    path('<slug:city>/maps', views.map, name='map_home'),
    path('<slug:city>/maps/<slug:type>', views.map, name='map'),
    path('<slug:city>/datasets', views.datasets, name='datasets'),
    path('<slug:city>/resources/photos', views.photos, name='photos'),
    path('<slug:city>/resources/<slug:slug>', views.resources, name='resources'),
    path('<slug:city>/datasets/<int:id>', views.dataset, name='dataset'),
    path('<slug:city>/datasets/<int:id>/delete', views.delete_dataset, name='delete_dataset'),
    path('<slug:city>/datasets/<int:dataset>/graph/<int:id>', views.graph, name='graph'),
    path('<slug:city>/datasets/<int:id>/<slug:slug>', views.dataset, name='dataset_slice'),
    path('<slug:city>/information', views.information_form, name='information_form'),
    path('<slug:city>/information/topic/<int:topic>', views.information_form, name='information_form_topic'),
    path('<slug:city>/information/<int:id>', views.information_form, name='information_form'),
    path('<slug:city>/photo', views.photo_form, name='photo_form'),
    path('<slug:city>/photo/<int:id>', views.photo_form, name='photo_form'),
    path('<slug:city>/sectors/<slug:sector>', views.sector, name='sector'),

    # Uploading data
    path('<slug:city>/upload', views.upload, name='upload'),

    # Uploading infrastructure data
    path('<slug:city>/upload/infrastructure', views.upload_infrastructure, name='upload_infrastructure'),
    path('<slug:city>/upload/infrastructure/<slug:type>', views.upload_infrastructure_file, name='upload_infrastructure_file'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>', views.upload_infrastructure_review, name='upload_infrastructure_review'),
    path('<slug:city>/upload/infrastructure/<slug:type>/<int:id>/meta', views.upload_infrastructure_meta, name='upload_infrastructure_meta'),

    # Uploading flows/stocks data
    path('<slug:city>/upload/flow', views.upload_flow, name='upload_flow'),
    path('<slug:city>/upload/flow/<int:id>', views.upload_flow_file, name='upload_flow_file'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>', views.upload_flow_review, name='upload_flow_review'),
    path('<slug:city>/upload/flow/<int:type>/<int:id>/meta', views.upload_flow_meta, name='upload_flow_meta'),
    path('<slug:city>/upload/stock', views.upload_flow, {'type': 'stocks'}, name='upload_stock'),

    path('<slug:city>/infrastructure/<slug:type>/<slug:space>', views.space, name='space'),
    path('<slug:city>/infrastructure/<slug:type>', views.space_list, name='space_list'),
    path('<slug:city>/infrastructure/<slug:topic>', views.infrastructure_list, name='infrastructure_list'),
    path('<slug:city>/infrastructure', views.infrastructure_list, name='infrastructure_list'),
    path('<slug:city>/<slug:main>/<slug:topic>', views.topic, name='subtopic'),
    path('<slug:city>/<slug:main>/<slug:topic>/input', views.topic, {'tab': 'input'}, name='subtopic_input'),
    path('<slug:city>/<slug:main>/<slug:topic>/use', views.topic, {'tab': 'use' }, name='subtopic_use'),
    path('<slug:city>/<slug:main>/<slug:topic>/output', views.topic, {'tab': 'output'}, name='subtopic_output'),
    #path('<slug:city>/<slug:theme>/<slug:topic>/<slug:type>', views.space_list, name='space_list'),

    path('materials', views.materials, name='materials'),
    path('<slug:slug>', views.detail, name='city'),
    path('profile', views.detail, name='profile'),

]

src/multiplicity/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from tinymce import HTMLField
from django.forms import ModelForm

# Used for image resizing
from stdimage.models import StdImageField
import re

User = get_user_model()

class TimestampedModel(models.Model):
    # A timestamp representing when this object was created.
    created_at = models.DateTimeField(auto_now_add=True)

    # A timestamp reprensenting when this object was last updated.
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

        # By default, any model that inherits from `TimestampedModel` should
        # be ordered in reverse-chronological order. We can override this on a
        # per-model basis as needed, but reverse-chronological is a good
        # default ordering for most models.
        ordering = ['-created_at', '-updated_at']

class Topic(models.Model):
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(db_index=True, max_length=255, unique=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    position = models.PositiveSmallIntegerField()
    description = models.TextField(null=True, blank=True)
    materials = models.ManyToManyField('staf.Material', blank=True)
    deleted = models.BooleanField(default=False, db_index=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ["position"]

class ReferenceSpaceType(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(db_index=True, max_length=255, unique=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True)
    process = models.ForeignKey('staf.Process', on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'slug__isnull': False})
    SPACE_TYPE = (
        ('SOC', 'Socio-economic System'),
        ('NAT', 'Natural Environment'),
    )
    type = models.CharField(max_length=3, choices=SPACE_TYPE)
    COLORS = (
        ('blue', 'Blue'),
        ('red', 'Red'),
        ('green', 'Green'),
        ('darkblue', 'Dark Blue'),
        ('purple', 'Purple'),
        ('yellow', 'yellow'),
        ('orange', 'Orange'),
        ('black', 'Black'),
        ('grey', 'Grey'),
        ('pink', 'Pink'),
        ('brightgreen', 'Bright green'),
        ('white', 'White'),
    )
    marker_color = models.CharField(max_length=10, choices=COLORS, null=True, blank=True, default='blue')
    user_accessible = models.BooleanField()
    def __str__(self):
        return self.name

    def features(self):
        return Feature.objects.filter(type=self.id, show_in_table=True)

class DatasetTypeStructure(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(db_index=True, max_length=255)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    icon = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

class DatasetType(models.Model):
    name = models.CharField(max_length=255)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    origin_process = models.ForeignKey('staf.Process', on_delete=models.CASCADE, null=True, blank=True, related_name='origindataset')
    destination_process = models.ForeignKey('staf.Process', on_delete=models.CASCADE, null=True, blank=True, related_name='destinationdataset')
    standard_material = models.ForeignKey('staf.Material', on_delete=models.CASCADE, null=True, blank=True)
    origin_reference_type = models.ForeignKey(ReferenceSpaceType, on_delete=models.CASCADE, null=True, blank=True, related_name='originreferencetype')
    destination_reference_type = models.ForeignKey(ReferenceSpaceType, on_delete=models.CASCADE, null=True, blank=True, related_name='destinationreferencetype')
    FLOWS = (
        ('destination_only', 'Destination only'),
        ('origin_only', 'Origin only'),
        ('origin_and_destination', 'Origin and destination'),
    )
    flows = models.CharField(max_length=25, choices=FLOWS, default='origin_and_destination')
    TYPES = (
        ('stocks', 'Stocks'),
        ('flows', 'Flows'),
    )
    type = models.CharField(max_length=6, choices=TYPES, default='flows')
    image = models.ImageField(null=True, blank=True, upload_to='datasettype')
    category = models.ForeignKey(DatasetTypeStructure, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    active = models.BooleanField()

    def __str__(self):
        if self.category:
            return '%s (%s)' % (self.name, self.category.name)
        else:
            return self.name

    class Meta:
        ordering = ["name"]

class DatasetTypeForm(ModelForm):
    class Meta:
        model = DatasetType
        fields = ['name', 'description', 'flows', 'type', 'category', 'topic', 'slug', 'active']


class ReferenceSpace(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    type = models.ForeignKey(ReferenceSpaceType, on_delete=models.CASCADE)
    city = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='city_location')
    country = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='country_location')
    description = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(db_index=True, max_length=255, null=True)
    location = models.ForeignKey('multiplicity.ReferenceSpaceLocation', on_delete=models.SET_NULL, null=True, blank=True)
    csv = models.ForeignKey('multiplicity.ReferenceSpaceCSV', on_delete=models.CASCADE, null=True, blank=True)
    tag = models.ForeignKey('core.Tag', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name + " (" + self.type.name + ")"
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)
        super(ReferenceSpace, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name"]

class ReferenceSpaceForm(ModelForm):
    class Meta:
        model = ReferenceSpace
        fields = ['name', 'type', 'country']

class ReferenceSpaceLocation(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    space = models.ForeignKey(ReferenceSpace, on_delete=models.CASCADE)
    lat = models.CharField(max_length=20, null=True, blank=True)
    lng = models.CharField(max_length=20, null=True, blank=True)
    default_zoom = models.PositiveSmallIntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    timeframe = models.CharField(max_length=255, null=True, blank=True)
    source = models.CharField(max_length=255, null=True, blank=True)
    geojson = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.name or 'Location for ' + self.space.name
    class Meta:
        ordering = ["name"]

class ReferenceSpaceLocationForm(ModelForm):
    class Meta:
        model = ReferenceSpaceLocation
        exclude = ['id', 'space']

class Feature(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    type = models.ForeignKey(ReferenceSpaceType, on_delete=models.CASCADE)
    unit = models.ForeignKey('staf.Unit', on_delete=models.CASCADE, null=True, blank=True)
    exclusively_for = models.ForeignKey(ReferenceSpace, on_delete=models.CASCADE, null=True, blank=True)
    show_in_table = models.BooleanField(default=False)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ["id"]

class ReferenceSpaceFeature(models.Model):
    space = models.ForeignKey(ReferenceSpace, on_delete=models.CASCADE)
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE)
    value = models.TextField()
    def __str__(self):
        return '%s for %s' % (self.feature, self.space)

class ReferenceSpaceTypeDescription(models.Model):
    type = models.ForeignKey(ReferenceSpaceType, on_delete=models.CASCADE)
    space = models.ForeignKey(ReferenceSpace, on_delete=models.CASCADE)
    description = models.TextField()

class ReferenceSpaceCSV(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.ForeignKey(ReferenceSpaceType, on_delete=models.CASCADE)
    space = models.ForeignKey(ReferenceSpace, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    original_name = models.CharField(max_length=255)
    imported = models.BooleanField()
    how_obtained = models.TextField(null=True, blank=True)
    gaps = models.TextField(null=True, blank=True)
    source = models.CharField(max_length=255, null=True, blank=True)

class DQI(models.Model):
    name = models.CharField(max_length=40)
    def __str__(self):
        return self.name

class DQIRating(models.Model):
    indicator = models.ForeignKey(DQI, on_delete=models.CASCADE, null=True, blank=True)
    score = models.PositiveSmallIntegerField()
    description = models.CharField(max_length=255)
    def __str__(self):
        return "Rating " + str(self.score) + " - " + self.indicator.name
    class Meta:
        ordering = ["score"]

class ProcessGroup(models.Model):
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(db_index=True, max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)

src/templates/multiplicity/admin/cities.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Cities | Back-end {% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="./"><i class="pli-home"></i></a></li>
  <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
  <li class="active">Cities</li>
</ol>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-body">
        <div class="panel-heading">
            <h3>Cities</h3>
        </div>
          <div class="panel-body">
            <table class="table table-striped datatable">
              <thead>
                <tr>
                  <th>City</th>
                  <th>Country</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                {% for info in list %}
                  <tr>
                    <td><a href="{% url 'multiplicity:admin_city' info.id %}">{{ info.name }}</a></td>
                    <td>{{ info.country.name }}</td>
                    <td><a href="{% if info.location.id %}{% url 'multiplicity:admin_location' info.location.id %}{% else %}{% url 'multiplicity:admin_city_location' info.id %}{% endif %}">Location</a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

<p><a href="{% url 'multiplicity:admin_city_create' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Create new city</a></p>

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
{% endblock %}

{% block footer %}

{% endblock %}

src/templates/multiplicity/admin/datasettypes.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Dataset types | Back-end {% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="./"><i class="pli-home"></i></a></li>
  <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
  <li class="active">Dataset types</li>
</ol>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-body">
        <div class="panel-heading">
            <h3>Dataset types</h3>
        </div>
          <div class="panel-body">
            <table class="table table-striped table-fullwidth">
              <thead>
                <tr>
                  <th>Dataset</th>
                  <th>Flows/stock</th>
                  <th>Type</th>
                  <th>Category</th>
                </tr>
              </thead>
              <tbody>
                {% for info in list %}
                  <tr>
                    <td><a href="{% url 'multiplicity:admin_datasettype' info.id %}">{{ info.name }}</a></td>
                    <td>{{ info.get_type_display }}</td>
                    <td>{{ info.get_flows_display }}</td>
                    <td>{{ info.category }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

<p><a href="{% url 'multiplicity:admin_datasettype' %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Create new dataset type</a></p>

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
{% endblock %}

{% block footer %}

{% endblock %}

src/templates/multiplicity/admin/overview.data.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}{{ info.name }} | {{ info.country }}{% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}

<ol class="breadcrumb">
  <li><a href="./"><i class="pli-home"></i></a></li>
  <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
  <li><a href="{% url 'multiplicity:admin_referencespaces' info.type.slug %}">{{ info.type.name }}</a></li>
  <li>{{ info.name }}</li>
  <li class="active">Data overview</li>
</ol>

{% if datasets %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <p><a href="{% url 'multiplicity:city' info.slug %}" class="btn btn-info">View {{ info.name }} online</a></p>
        <h3>Datasets</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>User</th>
                    <th>Creation date</th>
                </tr>
            </thead>
            <tbody>
            {% for details in datasets %}
                <tr>
                    <td><a href="{% url 'multiplicity:dataset' info.slug details.id %}">{{ details.name }}</a></td>
                    <td>{{ details.type.name }}</td>
                    <td>
                      {% for csv in details.csv_set.all %}
                        {{ csv.user }}<br>
                      {% endfor %}
                    </td>
                    <td>
                      {% for csv in details.csv_set.all %}
                        {{ csv.created_at|date:"M d, Y H:i" }}<br>
                      {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if csv %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>CSV Files - datasets</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Creation date</th>
                    <th>Name</th>
                    <th>User</th>
                    <th>Dataset</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in csv %}
                <tr>
                    <td data-sort="{{ details.created_at|date:"Y-m-d H:i" }}">{{ details.created_at }}</td>
                    <td><a href="{% url 'multiplicity:upload_flow_review' info.slug details.datasettype.id details.id %}">{{ details.original_name }}</a></td>
                    <td><a href="{% url 'core:userdetails' details.user.id %}">{{ details.user.first_name }} {{ details.user.last_name }}</a></td>
                    <td>
                    {% if details.dataset %}
                      <a href="{% url 'multiplicity:dataset' info.slug details.dataset.id %}">#{{ details.dataset.id }}</a>
                    {% endif %}
                    </td>
                    <td>{{ details.datasettype.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if space_csv %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>CSV Files - reference spaces</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Creation date</th>
                    <th>Name</th>
                    <th>User</th>
                    <th>Import?</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in space_csv %}
                <tr>
                    <td data-sort="{{ details.created_at|date:"Y-m-d H:i" }}">{{ details.created_at }}</td>
                    <td><a href="{% url 'multiplicity:upload_infrastructure_review' info.slug details.type.slug details.id %}">{{ details.original_name }}</a></td>
                    <td><a href="{% url 'core:userdetails' details.user.id %}">{{ details.user.first_name }} {{ details.user.last_name }}</a></td>
                    <td>
                    {% if details.imported %}
                      Yes
                    {% endif %}
                    </td>
                    <td>{{ details.type.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if information %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Information</h3>

        <ul>
          {% for details in information %}
            <li><a href="{% url 'multiplicity:information_form' info.slug details.id %}">{{ details.title }}</a></li>
          {% endfor %}
        </ul>
        
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if spaces %}

<div class="row">
  <div class="col">
    <div class="panel">
      <div class="panel-body">
        <h3>Reference spaces</h3>
        <table class="table table-striped datatable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
            {% for details in spaces %}
                <tr>
                    <td><a href="{% url 'multiplicity:space' info.slug details.type.slug details.slug %}">{{ details.name }}</a></td>
                    <td>{{ details.type.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %}

{% if photos %}

  <div class="panel">
    {% for details in photos %}
      <a href="{% url 'multiplicity:photo_form' info.slug details.id %}"><img src="{{ details.image.thumbnail.url }}" alt="" /></a>
    {% endfor %}
  </div>

{% endif %}

<p><a href="{% url 'multiplicity:photo_form' info.slug %}">Add new photo</a></p>

{% if referencephotos %}

  <div class="panel">
    {% for details in referencephotos %}
      <a href="{% url 'multiplicity:photo_form' info.slug details.id %}"><img src="{{ details.image.thumbnail.url }}" alt="" /></a>
    {% endfor %}
  </div>

{% endif %}

<p><a href="{% url 'multiplicity:admin_referencephoto' %}">Add new reference photo</a></p>


{% endblock %}

{% block head %}
<style type="text/css">
textarea.form-control{height:200px}
</style>
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block footer %}

{% endblock %}

src/templates/multiplicity/admin/referencespaces.html
{% extends 'multiplicity/base.html' %}
{% load static %}

{% block title %}Cities | Back-end {% endblock %}
{% block container %}stretch-bg-head{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="./"><i class="pli-home"></i></a></li>
  <li><a href="{% url 'team:controlpanel' %}">Back-end</a></li>
  <li class="active">{{ type.name }}</li>
</ol>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-body">
        <div class="panel-heading">
            <h3>{{ type.name }}</h3>
        </div>
          <div class="panel-body">
            <table class="table table-striped datatable">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Country</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                {% for info in list %}
                  <tr>
                    <td><a href="{% url 'multiplicity:admin_referencespace' info.type.slug info.id %}">{{ info.name }}</a></td>
                    <td>{{ info.country.name }}</td>
                    <td><a href="{% if info.location.id %}{% url 'multiplicity:admin_location' info.location.id %}{% else %}{% url 'multiplicity:admin_referencespace_location' info.type.slug info.id %}{% endif %}">Location</a> | 
                      <a href="{% url 'multiplicity:admin_data_overview' info.slug %}">Data overview</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>

<p><a href="{% url 'multiplicity:admin_referencespace_create' type.slug %}" class="btn btn-success"><i class="fas fa-plus fa-fw"></i> Create new record</a></p>

{% endblock %}

{% block head %}
{% endblock %}

{% block sidebar %}
{% include 'multiplicity/sidebar.default.html' %}

{% endblock %}

{% block pagehead %}
{% endblock %}

{% block footer %}

{% endblock %}